### ISSUE TITLE
Suggestion - add a margin-top to content to account for the header being fixed

### ISSUE THREAD

**Issue by jzhu01** [franckuche/Tea-Cozy#2]
Seen here: https://github.com/franckuche/Tea-Cozy/blob/ae4eccbde3af82388213dd45ef5a650073c8f792/resources/style.css#L47-L56

Since the header is fixed, it overlaps with part of the beginning of the content. I recommend adding a margin-top to make sure the blocked content is moved down.

**Comment by franckuche** [comment]
ok i fixed it
