### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [franckuche/Tea-Cozy#5]
Great job on this project - I really liked how you used the target in your HTML nav links and appreciated your usage of flex properties throughout the code. In terms of improvements, I recommend adding a margin-top to content, and overriding the default padding on the ul items. 

If you’re in the mood for a challenge, I would look into implementing a mobile version of this page! Here's a link to get you started: https://www.w3schools.com/css/css_rwd_mediaqueries.asp. Keep up the fantastic work! ^_^

**Comment by franckuche** [comment]
ok thanks for your feedback
do not hesitate to take a look again
